# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hesap.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1123, 679)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(400, 40, 271, 101))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(260, 150, 211, 81))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(710, 160, 291, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.sayibir = QtWidgets.QLineEdit(self.centralwidget)
        self.sayibir.setGeometry(QtCore.QRect(190, 220, 261, 31))
        self.sayibir.setObjectName("sayibir")
        self.sayiiki = QtWidgets.QLineEdit(self.centralwidget)
        self.sayiiki.setGeometry(QtCore.QRect(670, 220, 251, 31))
        self.sayiiki.setObjectName("sayiiki")
        self.topla = QtWidgets.QPushButton(self.centralwidget)
        self.topla.setGeometry(QtCore.QRect(150, 350, 101, 31))
        self.topla.setObjectName("topla")
        self.cikar = QtWidgets.QPushButton(self.centralwidget)
        self.cikar.setGeometry(QtCore.QRect(390, 350, 101, 31))
        self.cikar.setObjectName("cikar")
        self.carp = QtWidgets.QPushButton(self.centralwidget)
        self.carp.setGeometry(QtCore.QRect(650, 350, 101, 31))
        self.carp.setObjectName("carp")
        self.bol = QtWidgets.QPushButton(self.centralwidget)
        self.bol.setGeometry(QtCore.QRect(880, 350, 101, 31))
        self.bol.setObjectName("bol")
        self.sonuc = QtWidgets.QLabel(self.centralwidget)
        self.sonuc.setGeometry(QtCore.QRect(450, 450, 221, 101))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.sonuc.setFont(font)
        self.sonuc.setObjectName("sonuc")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1123, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.topla.clicked.connect(self.toplama)
        self.cikar.clicked.connect(self.cikarma)
        self.bol.clicked.connect(self.bolme)
        self.carp.clicked.connect(self.carpma)
    def toplama(self):     
        
        s1=self.sayibir.text()
        s2=self.sayiiki.text()
        islem=int(s1)+int(s2)
        self.sonuc.setText(str(islem))
        
        
    def cikarma(self):     
       
        s1=self.sayibir.text()
        s2=self.sayiiki.text()
        islem=int(s1)-int(s2)
        self.sonuc.setText(str(islem))
        
        
    def bolme(self):
        
        s1=self.sayibir.text()
        s2=self.sayiiki.text()
        islem=int(s1)%int(s2)
        self.sonuc.setText(str(islem))
        
    def carpma(self):
        
        s1=self.sayibir.text()
        s2=self.sayiiki.text()
        islem=int(s1)*int(s2)
        self.sonuc.setText(str(islem))
        
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "HESAP MAKİNESİ"))
        self.label_2.setText(_translate("MainWindow", "sayı1"))
        self.label_3.setText(_translate("MainWindow", "sayı2"))
        self.topla.setText(_translate("MainWindow", "TOPLAMA"))
        self.cikar.setText(_translate("MainWindow", "ÇIKARMA"))
        self.carp.setText(_translate("MainWindow", "ÇARPMA"))
        self.bol.setText(_translate("MainWindow", "BÖLME"))
        self.sonuc.setText(_translate("MainWindow", "SONUC"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
