# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1081, 638)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 80, 211, 151))
        self.groupBox.setObjectName("groupBox")
        self.rb_tost = QtWidgets.QRadioButton(self.groupBox)
        self.rb_tost.setGeometry(QtCore.QRect(0, 110, 111, 31))
        self.rb_tost.setObjectName("rb_tost")
        self.rb_tv = QtWidgets.QRadioButton(self.groupBox)
        self.rb_tv.setGeometry(QtCore.QRect(0, 70, 121, 21))
        self.rb_tv.setObjectName("rb_tv")
        self.rb_et = QtWidgets.QRadioButton(self.groupBox)
        self.rb_et.setGeometry(QtCore.QRect(0, 20, 121, 31))
        self.rb_et.setObjectName("rb_et")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(330, 90, 231, 141))
        self.groupBox_2.setObjectName("groupBox_2")
        self.rb_ayran = QtWidgets.QRadioButton(self.groupBox_2)
        self.rb_ayran.setGeometry(QtCore.QRect(10, 90, 121, 31))
        self.rb_ayran.setObjectName("rb_ayran")
        self.rb_su = QtWidgets.QRadioButton(self.groupBox_2)
        self.rb_su.setGeometry(QtCore.QRect(10, 20, 111, 31))
        self.rb_su.setObjectName("rb_su")
        self.rb_cay = QtWidgets.QRadioButton(self.groupBox_2)
        self.rb_cay.setGeometry(QtCore.QRect(10, 50, 111, 31))
        self.rb_cay.setObjectName("rb_cay")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(700, 90, 251, 141))
        self.groupBox_3.setObjectName("groupBox_3")
        self.rb_sut = QtWidgets.QRadioButton(self.groupBox_3)
        self.rb_sut.setGeometry(QtCore.QRect(10, 30, 121, 21))
        self.rb_sut.setObjectName("rb_sut")
        self.rb_pasta = QtWidgets.QRadioButton(self.groupBox_3)
        self.rb_pasta.setGeometry(QtCore.QRect(10, 60, 111, 21))
        self.rb_pasta.setObjectName("rb_pasta")
        self.rb_kek = QtWidgets.QRadioButton(self.groupBox_3)
        self.rb_kek.setGeometry(QtCore.QRect(10, 100, 95, 20))
        self.rb_kek.setObjectName("rb_kek")
        self.indirim = QtWidgets.QLineEdit(self.centralwidget)
        self.indirim.setGeometry(QtCore.QRect(340, 300, 171, 41))
        self.indirim.setObjectName("indirim")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(260, 290, 81, 51))
        self.label.setObjectName("label")
        self.vergi = QtWidgets.QLineEdit(self.centralwidget)
        self.vergi.setGeometry(QtCore.QRect(340, 360, 171, 41))
        self.vergi.setObjectName("vergi")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(260, 360, 71, 51))
        self.label_2.setObjectName("label_2")
        self.hesapla = QtWidgets.QPushButton(self.centralwidget)
        self.hesapla.setGeometry(QtCore.QRect(220, 450, 93, 28))
        self.hesapla.setObjectName("hesapla")
        self.topborc = QtWidgets.QLabel(self.centralwidget)
        self.topborc.setGeometry(QtCore.QRect(580, 460, 151, 51))
        self.topborc.setObjectName("topborc")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1081, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.araborc=0
        self.hangiy=0
        self.hangii=0
        self.rb_et.toggled.connect(self.etf)
        self.rb_tv.toggled.connect(self.tvf)
        self.rb_tost.toggled.connect(self.tostf)
        self.rb_su.toggled.connect(self.suf)
        self.rb_cay.toggled.connect(self.cayf)
        self.rb_ayran.toggled.connect(self.ayranf)
        self.rb_sut.toggled.connect(self.sutf)
        self.rb_pasta.toggled.connect(self.pastaf)
        self.rb_kek.toggled.connect(self.kekf)
        
    def etf(self):
        print("et seçtiniz ürün fiyatı 100TL")
        self.hangiy=1
    def tvf(self):
        print("tavuk seçtiniz ürün fiyatı 90TL")
        self.hangiy=2
    def tostf(self):
        print("tost seçtiniz ürün fiyatı 50TL")
        self.hangiy=3
        
        
    def suf(self):
        print("su seçtiniz ürün fiyatı 10TL")
        self.hangii=1
    def cayf(self):
        print("çay seçtiniz ürün fiyatı 20TL")
        self.hangii=2
    def ayranf(self):
        print("ayran seçtiniz ürün fiyatı 30TL")
        self.hangii=3
        
    
    def sutf(self):
        print("sütlaç seçtiniz ürün fiyatı 30TL")
        
    def pastaf(self):
        print("pasta seçtiniz ürün fiyatı 40TL")
        
    def kekf(self):
        print("kek seçtiniz ürün fiyatı 50TL")
        
        self.hesapla.clicked.connect(self.borcbul)
    def borcbul(self):
        if self.hangiy==1:
            self.araborc=self.araborc+100
            print(self.araborc)
        if self.hangiy==2:
            self.araborc=self.araborc+90
            print(self.araborc)
        if self.hangiy==3:
            self.araborc=self.araborc+50
            print(self.araborc)
            
        if self.hangii==1:
            self.araborc=self.araborc+10
            print(self.araborc)
        if self.hangii==2:
            self.araborc=self.araborc+20
            print(self.araborc)
        if self.hangii==3:
            self.araborc=self.araborc+30
            print(self.araborc)    
        
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "YİYECEKLER"))
        self.rb_tost.setText(_translate("MainWindow", "TOST: 50TL"))
        self.rb_tv.setText(_translate("MainWindow", "TAVUK: 90TL"))
        self.rb_et.setText(_translate("MainWindow", "ET SOTE: 100TL"))
        self.groupBox_2.setTitle(_translate("MainWindow", "İÇECEKLER"))
        self.rb_ayran.setText(_translate("MainWindow", "AYRAN: 30TL"))
        self.rb_su.setText(_translate("MainWindow", "SU: 10TL"))
        self.rb_cay.setText(_translate("MainWindow", "ÇAY:20 TL"))
        self.groupBox_3.setTitle(_translate("MainWindow", "TATLILAR"))
        self.rb_sut.setText(_translate("MainWindow", "SÜTLAÇ:30 TL"))
        self.rb_pasta.setText(_translate("MainWindow", "PASTA: 40TL"))
        self.rb_kek.setText(_translate("MainWindow", "KEK:50 TL"))
        self.label.setText(_translate("MainWindow", "İNDİRİM"))
        self.label_2.setText(_translate("MainWindow", "KDV"))
        self.hesapla.setText(_translate("MainWindow", "Hesapla"))
        self.topborc.setText(_translate("MainWindow", "TOPLAMBORC"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
