# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uyg.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(537, 413)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.urun = QtWidgets.QComboBox(self.centralwidget)
        self.urun.setGeometry(QtCore.QRect(20, 40, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.urun.setFont(font)
        self.urun.setObjectName("urun")
        self.urun.addItem("")
        self.urun.addItem("")
        self.urun.addItem("")
        self.adet = QtWidgets.QComboBox(self.centralwidget)
        self.adet.setGeometry(QtCore.QRect(150, 40, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.adet.setFont(font)
        self.adet.setObjectName("adet")
        self.adet.addItem("")
        self.adet.addItem("")
        self.adet.addItem("")
        self.adet.addItem("")
        self.adet.addItem("")
        self.ind = QtWidgets.QComboBox(self.centralwidget)
        self.ind.setGeometry(QtCore.QRect(280, 40, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.ind.setFont(font)
        self.ind.setObjectName("ind")
        self.ind.addItem("")
        self.ind.addItem("")
        self.ind.addItem("")
        self.kdv = QtWidgets.QComboBox(self.centralwidget)
        self.kdv.setGeometry(QtCore.QRect(410, 40, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.kdv.setFont(font)
        self.kdv.setObjectName("kdv")
        self.kdv.addItem("")
        self.kdv.addItem("")
        self.kdv.addItem("")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 10, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(160, 10, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(290, 10, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(420, 10, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.yap = QtWidgets.QPushButton(self.centralwidget)
        self.yap.setGeometry(QtCore.QRect(200, 140, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.yap.setFont(font)
        self.yap.setObjectName("yap")
        self.borc = QtWidgets.QLabel(self.centralwidget)
        self.borc.setGeometry(QtCore.QRect(150, 250, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.borc.setFont(font)
        self.borc.setObjectName("borc")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 537, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.yap.clicked.connect(self.hesap)
        #self.urun.addItem("Televizyon")
        sborc=0
        iborc=0
        kborc=0
        urunf=0
    def hesap(self):
            
            if self.urun.currentText()=="Tablet":
                urunf=1000
            elif self.urun.currentText()=="Telefon":
                urunf=2000
            elif self.urun.currentText()=="Tv":
                urunf=5000
            print("Ürün fiyatı",urunf)
            sborc=urunf*int(self.adet.currentText())
            print("ürün adeti",self.adet.currentText())
            print("indirimsiz borç",sborc)
            iborc=sborc-(sborc*int(self.ind.currentText())/100)
            print("indirim oranu",self.ind.currentText())
            print("indirimli borç",iborc)
            kborc=iborc+(iborc*int(self.kdv.currentText())/100)
            print("KDV oranı",self.kdv.currentText())
            print("KDVLi borç",kborc)

            self.borc.setText(str(kborc))
                         

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.urun.setItemText(0, _translate("MainWindow", "Tablet"))
        self.urun.setItemText(1, _translate("MainWindow", "Telefon"))
        self.urun.setItemText(2, _translate("MainWindow", "Tv"))
        self.adet.setItemText(0, _translate("MainWindow", "1"))
        self.adet.setItemText(1, _translate("MainWindow", "2"))
        self.adet.setItemText(2, _translate("MainWindow", "3"))
        self.adet.setItemText(3, _translate("MainWindow", "4"))
        self.adet.setItemText(4, _translate("MainWindow", "5"))
        self.ind.setItemText(0, _translate("MainWindow", "5"))
        self.ind.setItemText(1, _translate("MainWindow", "10"))
        self.ind.setItemText(2, _translate("MainWindow", "15"))
        self.kdv.setItemText(0, _translate("MainWindow", "10"))
        self.kdv.setItemText(1, _translate("MainWindow", "20"))
        self.kdv.setItemText(2, _translate("MainWindow", "25"))
        self.label.setText(_translate("MainWindow", "Ürün"))
        self.label_2.setText(_translate("MainWindow", "Adet"))
        self.label_3.setText(_translate("MainWindow", "İndirim"))
        self.label_4.setText(_translate("MainWindow", "Kdv"))
        self.yap.setText(_translate("MainWindow", "HESAPLA"))
        self.borc.setText(_translate("MainWindow", "BORÇ MİKTARI"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
